-- 1

SELECT
    EMPLOYEE_int,
    FIRST_NAME,
    LAST_NAME,
    DATEDIFF(YEAR, BIRTH_DATE, GETDATE()) AS Age,
    DATEDIFF(YEAR, HIRE_DATE, GETDATE()) AS Seniority
FROM EMPLOYEES
WHERE 
    TITLE IN ('Mr.', 'Dr.')
    AND (SALARY + ISNULL(COMMISSION, 0)) >= 8000
ORDER BY 
    Seniority DESC;

-- 2
SELECT 
    PRODUCT_REF,
    PRODUCT_NAME,
    SUPPLIER_int,
    UNITS_ON_ORDER,
    UNIT_PRICE, QUANTITY
FROM PRODUCTS
WHERE 
    QUANTITY LIKE '%bottles%'
    AND SUBSTRING(PRODUCT_NAME, 3, 1) IN ('t', 'T')
    AND SUPPLIER_int IN (1, 2, 3, 7) -- j'ai ajouté 7 pour vérifier la requête, si non pas de résultat
    AND UNIT_PRICE BETWEEN 70 AND 200
    AND UNITS_ON_ORDER IS NOT NULL;

--3
SELECT *
FROM CUSTOMERS
WHERE 
    COUNTRY = (SELECT COUNTRY FROM SUPPLIERS WHERE SUPPLIER_int = 1)
    AND CITY = (SELECT CITY FROM SUPPLIERS WHERE SUPPLIER_int = 1)
    AND RIGHT(POSTAL_CODE, 3) = RIGHT((SELECT POSTAL_CODE FROM SUPPLIERS WHERE SUPPLIER_int = 1), 3);

--4
SELECT 
    od.ORDER_int AS [Order Number],
    CASE 
        WHEN SUM(od.UNIT_PRICE * od.QUANTITY) BETWEEN 0 AND 2000 THEN '0%'
        WHEN SUM(od.UNIT_PRICE * od.QUANTITY) BETWEEN 2001 AND 10000 THEN '5%'
        WHEN SUM(od.UNIT_PRICE * od.QUANTITY) BETWEEN 10001 AND 40000 THEN '10%'
        WHEN SUM(od.UNIT_PRICE * od.QUANTITY) BETWEEN 40001 AND 80000 THEN '15%'
        ELSE '20%'
    END AS [New Discount Rate],
    CASE 
        WHEN od.ORDER_int < 11000 THEN 'apply old discount rate'
        ELSE 'apply new discount rate'
    END AS [Discount Rate Application Note]
FROM ORDER_DETAILS od
WHERE od.ORDER_int BETWEEN 10998 AND 11003
GROUP BY od.ORDER_int;

--5
SELECT DISTINCT 
    S.SUPPLIER_int AS [Supplier Number],
    S.COMPANY,
    S.ADDRESS,
    S.PHONE
FROM SUPPLIERS S
JOIN PRODUCTS P ON S.SUPPLIER_int = P.SUPPLIER_int
JOIN CATEGORIES C ON P.CATEGORY_CODE = C.CATEGORY_CODE
WHERE C.CATEGORY_NAME = 'Beverages';

--6
SELECT C.CUSTOMER_CODE
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
LEFT JOIN ORDER_DETAILS OD ON O.ORDER_int = OD.ORDER_int
LEFT JOIN PRODUCTS P ON OD.PRODUCT_REF = P.PRODUCT_REF
LEFT JOIN CATEGORIES CAT ON P.CATEGORY_CODE = CAT.CATEGORY_CODE
WHERE C.CITY = 'Berlin'
GROUP BY C.CUSTOMER_CODE
HAVING COUNT(CASE WHEN CAT.CATEGORY_NAME = 'Desserts' THEN 1 END) <= 1;

--7
SELECT 
    C.CUSTOMER_CODE AS [Customer Number],
    C.COMPANY AS [Company Name],
    C.PHONE,
    ISNULL(SUM(OD.UNIT_PRICE * OD.QUANTITY * (1 - OD.DISCOUNT)), 0) AS [Total Amount],
    C.COUNTRY
FROM CUSTOMERS C
LEFT JOIN ORDERS O 
    ON C.CUSTOMER_CODE = O.CUSTOMER_CODE 
    AND O.ORDER_DATE BETWEEN '1998-04-01' AND '1998-04-30'
    AND DATEPART(WEEKDAY, O.ORDER_DATE) = 2
LEFT JOIN ORDER_DETAILS OD ON O.ORDER_int = OD.ORDER_int
WHERE C.COUNTRY = 'France'
GROUP BY 
    C.CUSTOMER_CODE, C.COMPANY, C.PHONE, C.COUNTRY;

--8

SELECT 
    C.CUSTOMER_CODE,
    C.COMPANY AS [Company Name],
    C.PHONE AS [Telephone Number]
FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
JOIN ORDER_DETAILS OD ON O.ORDER_int = OD.ORDER_int
GROUP BY C.CUSTOMER_CODE, C.COMPANY, C.PHONE
HAVING COUNT(DISTINCT OD.PRODUCT_REF) = (SELECT COUNT(*) FROM PRODUCTS);


--9

SELECT 
    C.CUSTOMER_CODE,
    COUNT(O.ORDER_int) AS [Number of Orders]
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
WHERE C.COUNTRY = 'France'
GROUP BY C.CUSTOMER_CODE, C.COMPANY;


--10
SELECT
    (SELECT COUNT(*) FROM ORDERS WHERE YEAR(ORDER_DATE) = 1996) AS [Orders in 1996],
    (SELECT COUNT(*) FROM ORDERS WHERE YEAR(ORDER_DATE) = 1997) AS [Orders in 1997],
    (SELECT COUNT(*) FROM ORDERS WHERE YEAR(ORDER_DATE) = 1997) -
    (SELECT COUNT(*) FROM ORDERS WHERE YEAR(ORDER_DATE) = 1996) AS [Difference];
